# Generated by Django 5.0 on 2023-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_my_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future_plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='media/app')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
