# Generated by Django 5.0 on 2023-12-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_future_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_trust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='media/app')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
